// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    public partial class Bom
    {
        [Key]
        public long BomId { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string BomCode { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Version { get; set; }
        public long MaterialId { get; set; }
        public long? ParentId { get; set; }
        public byte? BomLevel { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        [Column(TypeName = "decimal(9, 4)")]
        public decimal? Amount { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }
    }
}