// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    [Index("BuyerCode", Name = "UC_Buyer_BuyerCode", IsUnique = true)]
    public partial class Buyer
    {
        public Buyer()
        {
            Material_Buyer = new HashSet<Material_Buyer>();
        }

        [Key]
        public long BuyerId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string BuyerCode { get; set; }
        [StringLength(200)]
        public string BuyerName { get; set; }
        public string Contact { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [InverseProperty("Buyer")]
        public virtual ICollection<Material_Buyer> Material_Buyer { get; set; }
    }
}