// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    public partial class ForecastPOMaster
    {
        public ForecastPOMaster()
        {
            ForecastPO = new HashSet<ForecastPO>();
        }

        [Key]
        public long FPoMasterId { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string FPoMasterCode { get; set; }
        public int? TotalOrderQty { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [InverseProperty("FPoMaster")]
        public virtual ICollection<ForecastPO> ForecastPO { get; set; }
    }
}