// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    public partial class Location
    {
        [Key]
        public long LocationId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string LocationCode { get; set; }
        public long AreaId { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("AreaId")]
        [InverseProperty("Location")]
        public virtual sysTbl_CommonDetail Area { get; set; }
    }
}