// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    public partial class Material_Supplier
    {
        [Key]
        public long MaterialId { get; set; }
        [Key]
        public long SupplierId { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("MaterialId")]
        [InverseProperty("Material_Supplier")]
        public virtual Material Material { get; set; }
        [ForeignKey("SupplierId")]
        [InverseProperty("Material_Supplier")]
        public virtual Supplier Supplier { get; set; }
    }
}