// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    [Index("MoldSerial", Name = "UC_MoldSerial", IsUnique = true)]
    public partial class Mold
    {
        [Key]
        public long MoldId { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string MoldSerial { get; set; }
        [Required]
        [StringLength(11)]
        [Unicode(false)]
        public string MoldCode { get; set; }
        public long Model { get; set; }
        public long MoldType { get; set; }
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? Inch { get; set; }
        public long MachineType { get; set; }
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? MachineTon { get; set; }
        [Precision(3)]
        public DateTime? ETADate { get; set; }
        public byte Cabity { get; set; }
        public bool? ETAStatus { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("MachineType")]
        [InverseProperty("MoldMachineTypeNavigation")]
        public virtual sysTbl_CommonDetail MachineTypeNavigation { get; set; }
        [ForeignKey("Model")]
        [InverseProperty("MoldModelNavigation")]
        public virtual sysTbl_CommonDetail ModelNavigation { get; set; }
        [ForeignKey("MoldType")]
        [InverseProperty("MoldMoldTypeNavigation")]
        public virtual sysTbl_CommonDetail MoldTypeNavigation { get; set; }
    }
}