// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    [Index("ProductCode", Name = "UC_ProductCode", IsUnique = true)]
    public partial class Product
    {
        [Key]
        public long ProductId { get; set; }
        [Required]
        [StringLength(11)]
        [Unicode(false)]
        public string ProductCode { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        public long Model { get; set; }
        public long ProductType { get; set; }
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? Inch { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("Model")]
        [InverseProperty("ProductModelNavigation")]
        public virtual sysTbl_CommonDetail ModelNavigation { get; set; }
        [ForeignKey("ProductType")]
        [InverseProperty("ProductProductTypeNavigation")]
        public virtual sysTbl_CommonDetail ProductTypeNavigation { get; set; }
    }
}