// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    [Index("QCCode", Name = "UC_QC_QCCode", IsUnique = true)]
    public partial class QC
    {
        public QC()
        {
            QCDetail = new HashSet<QCDetail>();
        }

        [Key]
        public long QCId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string QCCode { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [InverseProperty("QC")]
        public virtual ICollection<QCDetail> QCDetail { get; set; }
    }
}