// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    [Index("QCMasterId", "QCId", Name = "UC_QCMaster_QC_QCDetail", IsUnique = true)]
    public partial class QCDetail
    {
        [Key]
        public long QCDetailId { get; set; }
        public long QCMasterId { get; set; }
        public long QCId { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("QCId")]
        [InverseProperty("QCDetail")]
        public virtual QC QC { get; set; }
        [ForeignKey("QCMasterId")]
        [InverseProperty("QCDetail")]
        public virtual QCMaster QCMaster { get; set; }
    }
}