// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    [Index("roleName", Name = "UC_sysTbl_Role_roleName", IsUnique = true)]
    public partial class sysTbl_Role
    {
        public sysTbl_Role()
        {
            sysTbl_Role_Menu = new HashSet<sysTbl_Role_Menu>();
            sysTbl_Role_Permission = new HashSet<sysTbl_Role_Permission>();
            sysTbl_User_Role = new HashSet<sysTbl_User_Role>();
        }

        [Key]
        public long roleId { get; set; }
        [Required]
        [StringLength(50)]
        public string roleName { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [InverseProperty("role")]
        public virtual ICollection<sysTbl_Role_Menu> sysTbl_Role_Menu { get; set; }
        [InverseProperty("role")]
        public virtual ICollection<sysTbl_Role_Permission> sysTbl_Role_Permission { get; set; }
        [InverseProperty("role")]
        public virtual ICollection<sysTbl_User_Role> sysTbl_User_Role { get; set; }
    }
}