// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    [Index("commonMasterName", Name = "UC_sysTbl_CommonMaster_commonMasterName", IsUnique = true)]
    public partial class sysTbl_CommonMaster
    {
        public sysTbl_CommonMaster()
        {
            sysTbl_CommonDetail = new HashSet<sysTbl_CommonDetail>();
        }

        [Key]
        public long commonMasterId { get; set; }
        [Required]
        [StringLength(100)]
        public string commonMasterName { get; set; }
        public bool? forRoot { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [InverseProperty("commonMaster")]
        public virtual ICollection<sysTbl_CommonDetail> sysTbl_CommonDetail { get; set; }
    }
}