// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    public partial class sysTbl_Document
    {
        [Key]
        public long documentId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string menuComponent { get; set; }
        [StringLength(255)]
        public string urlFile { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string language { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }
    }
}