// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    public partial class sysTbl_CommonDetail
    {
        public sysTbl_CommonDetail()
        {
            Location = new HashSet<Location>();
            MaterialMaterialTypeNavigation = new HashSet<Material>();
            MaterialUnitNavigation = new HashSet<Material>();
            MoldMachineTypeNavigation = new HashSet<Mold>();
            MoldModelNavigation = new HashSet<Mold>();
            MoldMoldTypeNavigation = new HashSet<Mold>();
            ProductModelNavigation = new HashSet<Product>();
            ProductProductTypeNavigation = new HashSet<Product>();
            Tray = new HashSet<Tray>();
            sysTbl_Permission = new HashSet<sysTbl_Permission>();
        }

        [Key]
        public long commonDetailId { get; set; }
        public long commonMasterId { get; set; }
        [Required]
        [StringLength(100)]
        public string commonDetailName { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("commonMasterId")]
        [InverseProperty("sysTbl_CommonDetail")]
        public virtual sysTbl_CommonMaster commonMaster { get; set; }
        [InverseProperty("Area")]
        public virtual ICollection<Location> Location { get; set; }
        [InverseProperty("MaterialTypeNavigation")]
        public virtual ICollection<Material> MaterialMaterialTypeNavigation { get; set; }
        [InverseProperty("UnitNavigation")]
        public virtual ICollection<Material> MaterialUnitNavigation { get; set; }
        [InverseProperty("MachineTypeNavigation")]
        public virtual ICollection<Mold> MoldMachineTypeNavigation { get; set; }
        [InverseProperty("ModelNavigation")]
        public virtual ICollection<Mold> MoldModelNavigation { get; set; }
        [InverseProperty("MoldTypeNavigation")]
        public virtual ICollection<Mold> MoldMoldTypeNavigation { get; set; }
        [InverseProperty("ModelNavigation")]
        public virtual ICollection<Product> ProductModelNavigation { get; set; }
        [InverseProperty("ProductTypeNavigation")]
        public virtual ICollection<Product> ProductProductTypeNavigation { get; set; }
        [InverseProperty("TrayTypeNavigation")]
        public virtual ICollection<Tray> Tray { get; set; }
        [InverseProperty("commonDetail")]
        public virtual ICollection<sysTbl_Permission> sysTbl_Permission { get; set; }
    }
}