// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuizAPI.Models
{
    [Index("WoCode", Name = "UC_WorkOrder_WoCode", IsUnique = true)]
    public partial class WorkOrder
    {
        [Key]
        public long WoId { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string WoCode { get; set; }
        public long? PoId { get; set; }
        public long MaterialId { get; set; }
        public long? LineId { get; set; }
        public int OrderQty { get; set; }
        [Precision(0)]
        public DateTime? StartDate { get; set; }
        public int? ActualQty { get; set; }
        [Required]
        public bool? isActived { get; set; }
        [Precision(3)]
        public DateTime createdDate { get; set; }
        public long createdBy { get; set; }
        [Precision(3)]
        public DateTime? modifiedDate { get; set; }
        public long? modifiedBy { get; set; }
        public byte[] row_version { get; set; }

        [ForeignKey("MaterialId")]
        [InverseProperty("WorkOrder")]
        public virtual Material Material { get; set; }
    }
}