// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>;
using QuizAPI.Models.Dtos.Common;

namespace QuizAPI.Models.Dtos
{
    public partial class MaterialDto : BaseModel
    {
        public long? MaterialId { get; set; }
        public string MaterialCode { get; set; }
        public string Description { get; set; }
        public long? MaterialType { get; set; }
        public long? Unit { get; set; }
        public string MaterialTypeName { get; set; }
        public string UnitName { get; set; }
        public IEnumerable<SupplierDto> Suppliers { get; set; }
        public string SupplierNames { get; set; }
        public string GroupMaterial { get; set; }

    }
}